name: Automatisation des tests DevSecOps
on: push

jobs:
  Dependances:
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Scan des dépendances avec Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: 'requirements.txt'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'

  Dockerfile:
    runs-on: ubuntu-latest
    needs: Dependances
    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Analyse de sécurité du Dockerfile avec Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          scan-ref: 'Dockerfile'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'

  Deploy:
    runs-on: ubuntu-latest
    needs: Dockerfile
    steps:
      - name: Deploy
        run: |
          echo "Rien à faire ici. Votre application est prête à être déployée"
